# Generated by Django 6.0.7 on 2026-07-23 07:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='備品名')),
                ('category', models.CharField(max_length=50, verbose_name='カテゴリ')),
                ('total_quantity', models.PositiveIntegerField(default=1, verbose_name='所持数')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='保管場所')),
                ('notes', models.TextField(blank=True, verbose_name='備考')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrower_name', models.CharField(max_length=100, verbose_name='借りた人')),
                ('due_date', models.DateField(verbose_name='返却予定日')),
                ('loaned_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='貸出日時')),
                ('returned_at', models.DateTimeField(blank=True, null=True, verbose_name='返却日時')),
                ('memo', models.TextField(blank=True, verbose_name='メモ')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='inventory.item', verbose_name='備品')),
            ],
            options={
                'ordering': ['returned_at', '-loaned_at'],
            },
        ),
    ]
